name: Angular release

on:
    workflow_call:
        inputs:
            project-name:
                type: string
                description: 'the project name'
                required: true
            version:
                type: string
                description: 'the version bump to perform'
                required: true
            version-postfix:
                type: string
                description: 'the version postfix to add to the tag'
                required: false
            tag-latest:
                type: boolean
                default: false  
                required: false

jobs:
    release-angular:
        name:   Create quaker release
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3
            
            - name: Checkout ov-core-gitops
              uses: actions/checkout@v3
              with:
                repository: Ajaynano/ov-core-gitops
                token: ${{ secrets.PAT_PR }}
                path: 'ov-core-gitops'
                persist-credentials: true
                ref: 'develop'
            - name:  Build admin ui
              run: echo builing UI
            
            - name: Build container and push to dev
              id: admin-ui-dev
              if: ${{ inputs.tag-latest && github.ref == 'refs/remotes/origin/main'}}
              run: |
                echo ${{ inputs.tag-latest }}
                echo ${{ inputs.version }}

            - name: update dev k8 manifest
              if: ${{ success() && steps.admin-ui-dev.outcome == 'success' }}
              working-directory: ov-core-gitops
              run: |
                sed -i '/^admin-ui:/{n;s/imageVersion:.*/imageVersion:\ ${{ inputs.version }}${{ inputs.version-postfix }}/;}' ovc-app/config/envs/test/values-version.yaml
                git add -A
                git config --global user.name github-actions
                git config user.email github-actions@github.com
                git commit -m "Auto-generated by workflow. update app version to ${{ inputs.version }}-${{ github.sha }}"
                git push 

