name: Front end release

on:
  workflow_dispatch:
    inputs:
        admin-ui:
          type: boolean
          description: Release admin-ui
        version:
            type: string
        environment:
            type: choice
            options:
                - Dev
                - Int
                - Prod
jobs:
    release-admin-ui-dev:
        name: create Release for admin ui dev
        if: ${{ inputs.admin-ui && inputs.environment == 'Dev'}}
        uses: ./.github/workflows/angular-release.yaml
        with:
            project-name: 'admin-ui'
            version: ${{ inputs.version }}
            version-postfix: '-dev'
            tag-latest: true
        secrets: inherit
        
    release-admin-ui-int:
        name: create Release for admin ui int
        if: ${{ inputs.admin-ui && inputs.environment == 'Int'}}
        uses: ./.github/workflows/angular-release.yaml
        with:
            project-name: 'admin-ui'
            version: ${{ inputs.version }}
            version-postfix: '-int'
            tag-latest: true
        secrets: inherit    

    release-admin-ui-prod:
        name: create Release for admin ui production
        if: ${{ inputs.admin-ui && inputs.environment == 'Prod'}}
        uses: ./.github/workflows/angular-prod-release.yaml
        with:
            project-name: 'admin-ui'
        secrets: inherit   
            
