name: Back-end update int release

on:
    workflow_call:
        inputs:
            project-name:
                type: string
                description: 'the project name'
                required: true
            version:
                type: string
                description: 'the version bump to perform'
                required: true
            version-postfix:
                type: string
                description: 'the version postfix to add to the tag'
                required: false
            tag-latest:
                type: boolean
                default: false  
                required: false

jobs:
    release-quarkus:
        name:   Create quaker release
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3
            
            - name: Checkout ov-core-gitops
              uses: actions/checkout@v3
              with:
                repository: Ajaynano/ov-core-gitops
                token: ${{ secrets.PAT_PR }}
                path: 'ov-core-gitops'
                persist-credentials: true
                fetch-depth: '0'
            - name:  Build backend service
              run: echo builing ${{ inputs.project-name }}
            
            - name: Build container and push to int
              id: backend
              if: ${{ inputs.tag-latest && github.ref == 'refs/heads/release' }}
              run: |
                echo ${{ inputs.tag-latest }}
                echo ${{ inputs.version }}
                echo "added new code"
            
            - name: Create Pull Request 
              id: mainfest-update
              if: ${{ success() && steps.backend.outcome == 'success' }}
              uses: peter-evans/create-pull-request@v6
              with:
                token: ${{ secrets.PAT_PR }}
                commit-message: Updated git-ops repo int release
                committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
                author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
                signoff: false
                branch: develop
                base: release
                delete-branch: true
                title: '[Example] Update report'
                body: |
                  - Updated with *today's* date
                  - Auto-generated by [create-pull-request][1]

                  [1]: https://github.com/peter-evans/create-pull-request
                labels: |
                  report
                  automated pr
                assignees: Ajaynano
                reviewers: Ajaynano
                draft: false
           