name: Back-end prod  release

on:
    workflow_call:
        inputs:
            project-name:
                type: string
                description: 'the project name'
                required: true
jobs:
    release-quarkus:
        name:   Create quaker release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout ov-core-gitops
              uses: actions/checkout@v3
              with:
                repository: Ajaynano/ov-core-gitops
                token: ${{ secrets.PAT_PR }}
                path: 'ov-core-gitops'
                persist-credentials: true
                fetch-depth: '0'
            - name:  Build backend service
              run: echo builing ${{ inputs.project-name }}
            
            - name: update prod k8 manifest
              id: mainfest-update-prod
              if: ${{ github.ref == 'refs/heads/main' }}
              working-directory: ov-core-gitops
              run: |
                BRANCH_NAME="release"
                git checkout $BRANCH_NAME
                int_version="`awk '$1 == "imageVersion:"{if (key == "${{ inputs.project-name }}:") print $NF; next } {key=$1}' ovc-app/config/envs/int/values-version.yaml`"
                echo $int_version
                sed -i '/^${{ inputs.project-name }}:/{n;s/imageVersion:.*/imageVersion:\ '$int_version'/;}' ovc-app/config/envs/prod/values-version.yaml
                git add -A
                git config --global user.name github-actions
                git config user.email github-actions@github.com
                git commit -m "Auto-generated by workflow. update app version to ${{ inputs.version }}-${{ github.sha }}"
                git push 
                # GitHub CLI.
                echo "${{ secrets.repo_read_PAT }}" > token.txt
                # create a PR to main from release
                gh auth login --with-token < token.txt
                gh pr create \
                   --assignee Ajaynano \
                   --body "updating int manifestfile" \
                   --title "chore: update mainfest file" \
                   --head "$BRANCH_NAME" \
                   --base "main" 
