name: Back-end int  release

on:
    workflow_call:
        inputs:
            project-name:
                type: string
                description: 'the project name'
                required: true
            version:
                type: string
                description: 'the version bump to perform'
                required: true
            version-postfix:
                type: string
                description: 'the version postfix to add to the tag'
                required: false
            tag-latest:
                type: boolean
                default: false  
                required: false

jobs:
    release-quarkus:
        name:   Create quaker release
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3
            
            - name: Checkout ov-core-gitops
              uses: actions/checkout@v3
              with:
                repository: Ajaynano/ov-core-gitops
                token: ${{ secrets.PAT_PR }}
                path: 'ov-core-gitops'
                persist-credentials: true
                ref: 'develop'
            - name:  Build backend service
              run: echo builing ${{ inputs.project-name }}
            
            - name: Build container and push to int
              id: backend
              if: ${{ inputs.tag-latest && github.ref == 'refs/heads/release' }}
              run: |
                echo ${{ inputs.tag-latest }}
                echo ${{ inputs.version }}
                echo "added new code"
            
            - name: update dev k8 manifest
              id: mainfest-update
              if: ${{ success() && steps.backend.outcome == 'success' }}
              working-directory: ov-core-gitops
              run: |
                BRANCH_NAME="develop"
                git checkout $BRANCH_NAME
                sed -i '/^${{ inputs.project-name }}:/{n;s/imageVersion:.*/imageVersion:\ ${{ inputs.version }}${{ inputs.version-postfix }}/;}' ovc-app/config/envs/int/values-version.yaml
                git add -A
                git config --global user.name github-actions
                git config user.email github-actions@github.com
                git commit -m "Auto-generated by workflow. update app version to ${{ inputs.version }}-${{ github.sha }}"
                git push 
                # GitHub CLI.
                echo "${{ secrets.repo_read_PAT }}" > token.txt
                # create a PR to release from develop
                gh auth login --with-token < token.txt
                gh pr create --assignee Ajaynano --body "updating int manifestfile" --title "chore: update mainfest file" --head "$BRANCH_NAME" --base "release" || gh pr edit --assignee Ajaynano --body "updating int manifestfile" --title "chore: update mainfest file" --head "$BRANCH_NAME" --base "release"